version: "3.8"

services:
  web:
    build: .
    ports:
      - '8080:8080'
  postgres:
    image: postgis/postgis
    container_name: db
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hangzone
      - APP_DIR=/app
    ports:
      - 5432:5432
    volumes:
      - ./migrations:/app/migrations
      - ./scripts/db_init.sh:/docker-entrypoint-initdb.d/init.sh
  pgadmin-compose:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: "root@root.com"
            PGADMIN_DEFAULT_PASSWORD: "root"
        ports: 
            - "16543:80"
        depends_on: 
            - postgres   
