insert into user_hangers (id, first_name, last_name, alias, email_address, status_hang, status_description, icon_url, created_at, updated_at) values (1, 'Norene', 'Bernardot', 'Glyburide', 'nbernardot0@artisteer.com', 1, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'http://dummyimage.com/160x100.png/dddddd/000000', '2021-12-26 14:27:54', '2021-11-18 11:41:28');
insert into user_hangers (id, first_name, last_name, alias, email_address, status_hang, status_description, icon_url, created_at, updated_at) values (2, 'Chrissie', 'Kelso', 'Octinoxate', 'ckelso1@pagesperso-orange.fr', 1, 'Nam tristique tortor eu pede.', 'http://dummyimage.com/175x100.png/5fa2dd/ffffff', '2021-10-12 10:22:02', '2021-06-12 10:49:09');
insert into user_hangers (id, first_name, last_name, alias, email_address, status_hang, status_description, icon_url, created_at, updated_at) values (3, 'Gates', 'Kleinschmidt', 'simvastatin', 'gkleinschmidt2@tmall.com', 1, 'Sed ante. Vivamus tortor.', 'http://dummyimage.com/237x100.png/cc0000/ffffff', '2021-05-22 02:31:49', '2021-05-24 19:16:02');
insert into user_hangers (id, first_name, last_name, alias, email_address, status_hang, status_description, icon_url, created_at, updated_at) values (4, 'Wilek', 'Bohje', 'UREA', 'wbohje3@archive.org', 1, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 'http://dummyimage.com/205x100.png/cc0000/ffffff', '2021-07-17 11:31:56', '2022-01-22 23:31:42');
insert into user_hangers (id, first_name, last_name, alias, email_address, status_hang, status_description, icon_url, created_at, updated_at) values (5, 'Benita', 'Small', 'TITANIUM DIOXIDE, ZINC OXIDE and OCTINOXATE', 'bsmall4@wisc.edu', 2, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.', 'http://dummyimage.com/193x100.png/cc0000/ffffff', '2022-02-12 11:44:49', '2021-12-23 09:01:38');
insert into user_hangers (id, first_name, last_name, alias, email_address, status_hang, status_description, icon_url, created_at, updated_at) values (6, 'Tymothy', 'Sapson', 'PredniSONE', 'tsapson5@biglobe.ne.jp', 1, 'Vestibulum ac est lacinia nisi venenatis tristique.', 'http://dummyimage.com/135x100.png/dddddd/000000', '2021-07-06 15:02:18', '2021-03-23 13:10:30');
insert into user_hangers (id, first_name, last_name, alias, email_address, status_hang, status_description, icon_url, created_at, updated_at) values (7, 'Jada', 'Noddles', 'Cyclobenzaprine Hydrochloride', 'jnoddles6@tinyurl.com', 1, 'Cras pellentesque volutpat dui.', 'http://dummyimage.com/164x100.png/cc0000/ffffff', '2021-08-01 04:16:08', '2021-05-28 11:14:53');
insert into user_hangers (id, first_name, last_name, alias, email_address, status_hang, status_description, icon_url, created_at, updated_at) values (8, 'Adham', 'Mathias', 'triptorelin pamoate', 'amathias7@ezinearticles.com', 1, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'http://dummyimage.com/160x100.png/ff4444/ffffff', '2021-11-04 03:22:01', '2021-08-01 00:29:00');
insert into user_hangers (id, first_name, last_name, alias, email_address, status_hang, status_description, icon_url, created_at, updated_at) values (9, 'Red', 'Avey', 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 'ravey8@blogger.com', 1, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 'http://dummyimage.com/146x100.png/ff4444/ffffff', '2022-01-20 09:48:11', '2021-07-25 17:53:10');
insert into user_hangers (id, first_name, last_name, alias, email_address, status_hang, status_description, icon_url, created_at, updated_at) values (10, 'Dagny', 'Kaas', 'Zolmitriptan', 'dkaas9@ucoz.com', 1, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 'http://dummyimage.com/167x100.png/cc0000/ffffff', '2022-02-10 13:34:38', '2021-03-11 18:57:06');

